### PR TITLE
fixup! Castanets initial bringup commit.

### PR DESCRIPTION
**Pull request by suyambulingamrm**
Currently socket() call returns socket fd as 0 occasionally.
Though 0 is valid return value, the process communication
doesnot work properly. So as a workaround create & open a dummy
file so that the subsequent socket() call returns a non 0
sock fd.

Signed-off-by: suyambu.rm <suyambu.rm@samsung.com>

### CODE REVIEW

**Comment by is46-kim** [comment]
We can avoid zero fd with following step.
  if (!socket_handle) {
    int zero_fd = socket_handle;
    socket_handle = dup(zero_fd);
    close(zero_fd);
  }
This workaround is also needed in TCPServerAcceptConnection()

**Comment by suyambulingamrm** [comment]
Sure, I will incorporate this change

**Comment by suyambulingamrm** [comment]
Incorporated the changes. Now using dup() instead of file open.
As if (!socket_handle) include <0 cases also, I have handled 0 cases separately.

**Comment by is46-kim** [comment]
LGTM

**Pull request merged**
