### PR TITLE
[Service Offloading] Support Wifi Address API from JS

### PR DESCRIPTION
**Pull request by Chikdolman**
We need Wifi as a key for loading application from server.
Therefore we support wifi address function from JS.

### CODE REVIEW

**Comment by kenxiniz** [comment]
Could you please set the ip to "127.0.0.1" when network is off.

**Comment by Chikdolman** [comment]
> Could you please set the ip to "127.0.0.1" when network is off.

Done

**Review by kenxiniz — APPROVED** [review]
supporting ip address on javascript layer

**Review by Sunwoo-Nam — APPROVED** [review]
Looks good to me

**Pull request merged**
