### PR TITLE
Build application as docker image

### PR DESCRIPTION
**Pull request by rzr**
I am sharing a code that rely on other PR
that let you build a docker image from sources, as well as a debian package to deploy application more easily:

https://hub.docker.com/r/rzrfreefr/castanets/tags

https://dl.bintray.com/rzr/deb/pool/c/castanets-snapshot/

First please first merge this pending PR
https://github.com/Samsung/Castanets/pull/73

Then I can submit each patches individually.

Regards

### CODE REVIEW

**Review by Chikdolman — APPROVED** [review]
This looks good to me, and I don't think we need to merge #73 as this PR(#263 ) includes identical Makefile. How do you think?
I was also thinking about the Dockerfile for both easy setups and CRIU.
Thanks for your contribution :)

**Comment by rzr** [comment]
you can merge this PR once if preferred

**Comment by Chikdolman** [comment]
Android build failed due to system error. This commit does not affect the build. Thus it looks fine to merge this PR

**Comment by Chikdolman** [comment]
Can you also update Readme file for docker? :)

**Pull request merged**
