### PR TITLE
[Service Offloading] Android Input with Knox Activation Key Support

### PR DESCRIPTION
**Pull request by Chikdolman**
We split AsyncInitializationActivity for two cases.
1. When service_offloading is enabled, we use AsyncInitializationActivityKnox.java
2. When service_offloading is disabled, we use AsyncInitializationActivity.java
AsyncInitializationActivityKnox.java supports Knox activation key

### CODE REVIEW

**Review by yg48 — COMMENTED** [review]
Only difference is checking key part?
Then how about making sub class for this?
We can apply template method pattern.
https://en.wikipedia.org/wiki/Template_method_pattern

**Comment by Chikdolman** [comment]
> Only difference is checking key part?
> Then how about making sub class for this?
> We can apply template method pattern.
> https://en.wikipedia.org/wiki/Template_method_pattern

This patch enables compile-time build flag. There could be a better way. I'll check once again.

**Review by Sunwoo-Nam — APPROVED** [review]
LGTM

**Comment by Chikdolman** [comment]
Knox activation added

**Pull request merged**
