### PR TITLE
Enable gpu channel for rasterization

### PR DESCRIPTION
**Pull request by uzair-jaleel**
Enable gpu compositing and syncronize shared
memory for gpu command buffer and raterized data
between browser and renderer process.

Signed-off-by: Uzair Jaleel <uzair.jaleel@samsung.com>

### CODE REVIEW

**Comment by Chikdolman** [comment]
Is there a reason that this PR is a draft?

**Comment by uzair-jaleel** [comment]
> Is there a reason that this PR is a draft?

This change is good to go. but i am planing to add some more changes(patches) and then raise a pull request.

**Comment by Chikdolman** [comment]
We'll wait for it

**Comment by suyambulingamrm** [comment]
Shall we add waitsync apis also together ?
https://github.com/Samsung/Castanets/pull/231
https://github.com/Samsung/Castanets/pull/209/commits/92f1951fedca3f8cd5beb87054c5c0d0e343ccec
https://github.com/Samsung/Castanets/pull/243

**Comment by uzair-jaleel** [comment]
> Shall we add waitsync apis also together ?
> #231
> [92f1951](https://github.com/Samsung/Castanets/commit/92f1951fedca3f8cd5beb87054c5c0d0e343ccec)
> #243

done added

**Review by Chikdolman — APPROVED** [review]
Thanks for the effort.

**Comment by uzair-jaleel** [comment]
Fixed minor compiler error

**Pull request merged**
