### PR TITLE
Fix the issue that broken tiles are shown.

### PR DESCRIPTION
**Pull request by Sunwoo-Nam**
This issue occurs when resources are reused for tiles of different sizes.
If a mapped shared memory size is bigger than a tile size,
memory sync should be done with full shared memory size.
Memory sync is not supporting partial sync.

### CODE REVIEW

**Review by yg48 — COMMENTED** [review]
LGTM :)

**Review by hyowon — APPROVED** [review]
For now, when rasterizing and syncing a tile, we have to send all bytes of the shared memory used by the tile. An additional improvement task: https://github.com/Samsung/Castanets/issues/150

**Review by Chikdolman — APPROVED** [review]
We now have two reviews. I believe YG made a mistake to comment instead of approving.

**Comment by suyambulingamrm** [comment]
Can similar issue occur for downloaded resource transfer as well ?

**Comment by hyowon** [comment]
@suyambulingamrm
> Can similar issue occur for downloaded resource transfer as well?

You can see that the offset is 0 and the sync_size is the total size of the shared memory when calling the SyncSharedMemoryHandle() method in tile_manager.cc and one_copy_raster_buffer_provider.cc. On the other hand, the resource loader performs synchronization as much as the byte size written to the data_pipe. (See DataPipeProducerDispatcher::SyncData() in data_pipe_producer_dispatcher.cc.) So to summarize, the resource loader is already doing a partial synchronization.

**Comment by hyowon** [comment]
@suyambulingamrm
> Can similar issue occur for downloaded resource transfer as well?

Currently, there is a problem that some resources, especially such as images, are not displayed properly. Have you ever checked that those resources are downloaded (or cached?) resources?

**Pull request merged**
