### PR TITLE
[Meerkat] Change Meerkat Multicast IP

### PR DESCRIPTION
**Pull request by is46-kim**
- Change default multicast IP to 224.0.0.250
- Print all logs with "meerkat" log tag
- Join the thread to make sure that the thread stop when MeerkatServerService is destroyed
- This starts the MeerkatServer with multicast address from SettingProvider.

### CODE REVIEW

**Review by HunseopJeong — APPROVED** [review]
lgtm

**Review by Jw00 — APPROVED** [review]
LGTM

**Comment by hyunaranda** [comment]
lgtm

**Review by Chikdolman — COMMENTED** [review]
In mmSOCK/pTcpServer.cpp, can we apply following change also?
https://review.tizen.org/gerrit/#/c/platform/framework/web/chromium-efl/+/257172/3/tizen_src/meerkat/Component/mmSOCK/pTcpServer.cpp

**Comment by is46-kim** [comment]
> In mmSOCK/pTcpServer.cpp, can we apply following change also?
> https://review.tizen.org/gerrit/#/c/platform/framework/web/chromium-efl/+/257172/3/tizen_src/meerkat/Component/mmSOCK/pTcpServer.cpp

Done, I applied the change to edb8cd6

**Review by Chikdolman — APPROVED** [review]
LGTM

**Pull request merged**
