### PR TITLE
tool: Add Makefile to build deb package

### PR DESCRIPTION
**Pull request by rzr**
Even if project is using ninja as build system,
this top makefile can be used by packaging tool checkinstall
in a easier way.

Note: Snapshot prefix is used for publishing semi functionnal package.

Change-Id: Ib463526712fbe074353d2bc68d671a55a0e2f727
Relate-to: http://suprem.sec.samsung.net/jira/browse/TIZENWF-955
Signed-off-by: Philippe Coval <p.coval@samsung.com>

### CODE REVIEW

**Comment by suyambulingamrm** [comment]
As the repo is public, shall we remove the internal jira bug link from the commit msg.. ?

**Comment by suyambulingamrm** [comment]
LGTM..

**Comment by venumusham** [comment]
lgtm

**Comment by rzr** [comment]
Change ready to be reviewed

**Comment by rzr** [comment]
It was tested on current castanets_63 branch to build:
castanets-snapshot_0.0.0+73+gc7cd79b-0~0_amd64.deb

**Pull request closed without merging**
