### PR TITLE
fixup! Inform the browser of the shared memory created by the renderer.

### PR DESCRIPTION
**Pull request by hyowon**
Fix code location to erase create_buffers_.

### CODE REVIEW

**Review by Sunwoo-Nam — APPROVED** [review]
Looks good to me.

**Comment by suyambulingamrm** [comment]
I have a small clarification regarding to the original change, 
https://github.com/Samsung/Castanets/pull/237/commits/c1d168df3073bbc98c61ab8bd860b0905fdffed3#diff-c26b504a085cbddd80638db8ab023d0e.

Is there any specific reason we use sync_channel_ to send BUFFER_CREATED message, even there is no expected return data, unlike BUFFER_REQUEST message.  ?

When I verified this change, I see below errors on browser side.. (linux-android, tizen-tizen)

[14303:14306:0925/162733.087151:ERROR:channel.cc(642)] Invalid message size: 4286545791
[14303:14306:0925/162733.087212:ERROR:render_process_host_impl.cc(4538)] Terminating render process for bad Mojo message: Broker host received malformed messag
[14303:14306:0925/162733.087244:ERROR:bad_message.cc(25)] Terminating renderer for bad IPC message, reason 123

E/CHROMIUM(10555): [ERROR:channel.cc(642)] Invalid message size: 0
E/CHROMIUM(10555): [ERROR:render_process_host_impl.cc(4574)] Terminating render process for bad Mojo message: Broker host received malformed messag
E/CHROMIUM(10555): [ERROR:bad_message.cc(25)] Terminating renderer for bad IPC message, reason 123

there is no such errors, when we send BUFFER_CREATED message via broker channel using as below and WebGL case works fine.
`  channel_->Write(std::move(out_message)); `

**Comment by hyowon** [comment]
> Is there any specific reason we use sync_channel_ to send BUFFER_CREATED message, even there is no expected return data, unlike BUFFER_REQUEST message. ?

No, there was no particular reason for using sync_channel_. 

> there is no such errors, when we send BUFFER_CREATED message via broker channel using as below and WebGL case works fine.
> `channel_->Write(std::move(out_message));`

In Castanets mode over a TCP/IP connection, using `channel_->Write(std::move(out_message));` is correct. Thanks a lot.

**Comment by hyowon** [comment]
> there is no such errors, when we send BUFFER_CREATED message via broker channel using as below and WebGL case works fine.
> `channel_->Write(std::move(out_message));`

@suyambulingamrm Have you already created a CL for this fix? I should have included that fix in this PR. But I've unconsciously pressed the merge button. :(

**Comment by suyambulingamrm** [comment]
@hyowon Ok sure.. I have submitted https://github.com/Samsung/Castanets/pull/245 for this.

**Pull request merged**
